spring:
  application:
    name: food
  datasource:
    url: jdbc:postgresql://localhost:5432/food
    username: postgres
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  spring.jpa.show-sql: true
  spring.jpa.hibernate.ddl-auto: update

